"""初中 / 高中课标核心词汇范围（用于造句约束与校验提示）。"""

from __future__ import annotations

# 初中核心高频词（节选，覆盖日常与课标主干；造句时优先使用）
MIDDLE_SCHOOL_CORE = {
    "a", "about", "above", "across", "afraid", "after", "afternoon", "again", "against",
    "age", "ago", "agree", "air", "all", "almost", "alone", "along", "already", "also",
    "always", "am", "among", "an", "and", "angry", "animal", "another", "answer", "any",
    "anyone", "anything", "apple", "april", "are", "arm", "around", "arrive", "art", "as",
    "ask", "at", "august", "aunt", "autumn", "away", "baby", "back", "bad", "bag", "ball",
    "banana", "bank", "basketball", "be", "beach", "beautiful", "because", "become", "bed",
    "before", "begin", "behind", "believe", "bell", "below", "beside", "best", "better",
    "between", "big", "bike", "bird", "birthday", "bit", "black", "blackboard", "blow",
    "blue", "boat", "body", "book", "boring", "born", "both", "bottle", "box", "boy",
    "bread", "break", "breakfast", "bridge", "bright", "bring", "brother", "brown", "brush",
    "build", "bus", "busy", "but", "buy", "by", "cake", "call", "can", "candy", "cap",
    "car", "card", "care", "careful", "carry", "cat", "catch", "center", "chair", "change",
    "cheap", "child", "children", "china", "chinese", "choose", "cinema", "city", "class",
    "classmate", "classroom", "clean", "clear", "clever", "climb", "clock", "close", "clothes",
    "cloudy", "club", "coat", "coffee", "cold", "collect", "color", "come", "comfortable",
    "common", "computer", "concert", "cook", "cool", "copy", "corner", "correct", "cost",
    "could", "country", "course", "cousin", "cover", "cow", "crazy", "create", "cross",
    "cry", "culture", "cup", "cut", "dad", "daily", "dance", "danger", "dangerous", "dark",
    "date", "daughter", "day", "dead", "dear", "december", "decide", "deep", "delicious",
    "desk", "develop", "diary", "dictionary", "die", "difference", "different", "difficult",
    "dinner", "dirty", "discover", "discuss", "dish", "do", "doctor", "dog", "dollar",
    "door", "down", "draw", "dream", "dress", "drink", "drive", "driver", "drop", "dry",
    "duck", "during", "each", "ear", "early", "earth", "east", "easy", "eat", "egg",
    "eight", "eighteen", "either", "elephant", "eleven", "else", "email", "empty", "end",
    "enjoy", "enough", "enter", "environment", "even", "evening", "ever", "every",
    "everybody", "everyone", "everything", "example", "except", "excited", "exciting",
    "excuse", "exercise", "expect", "expensive", "explain", "eye", "face", "fact", "factory",
    "fail", "fall", "family", "famous", "far", "farm", "farmer", "fast", "fat", "father",
    "favorite", "february", "feel", "feeling", "festival", "few", "field", "fifteen", "fifth",
    "fifty", "fight", "fill", "film", "find", "fine", "finger", "finish", "fire", "first",
    "fish", "five", "fix", "floor", "flower", "fly", "follow", "food", "foot", "football",
    "for", "foreign", "forest", "forget", "form", "forty", "forward", "four", "fourteen",
    "free", "fresh", "friday", "friend", "friendly", "from", "front", "fruit", "full", "fun",
    "funny", "future", "game", "garden", "get", "gift", "girl", "give", "glad", "glass",
    "go", "goal", "god", "gold", "good", "goodbye", "grade", "grandfather", "grandmother",
    "grass", "great", "green", "ground", "group", "grow", "guess", "guitar", "habit", "hair",
    "half", "hall", "hand", "happen", "happy", "hard", "hardly", "hat", "hate", "have", "he",
    "head", "health", "healthy", "hear", "heart", "heavy", "hello", "help", "helpful", "her",
    "here", "hers", "herself", "hi", "high", "hill", "him", "himself", "his", "history",
    "hit", "hobby", "hold", "holiday", "home", "hometown", "homework", "hope", "horse",
    "hospital", "hot", "hotel", "hour", "house", "how", "however", "hundred", "hungry",
    "hurry", "hurt", "husband", "i", "ice", "idea", "if", "ill", "important", "in", "inside",
    "instead", "interest", "interesting", "internet", "into", "introduce", "invite", "is",
    "island", "it", "its", "itself", "january", "job", "join", "joke", "juice", "july",
    "jump", "june", "just", "keep", "key", "kick", "kid", "kill", "kind", "king", "kitchen",
    "knee", "knife", "know", "knowledge", "lab", "lady", "lake", "land", "language", "large",
    "last", "late", "later", "laugh", "law", "lay", "lazy", "learn", "least", "leave", "left",
    "leg", "less", "lesson", "let", "letter", "library", "lie", "life", "light", "like",
    "line", "lion", "list", "listen", "little", "live", "lively", "local", "lock", "long",
    "look", "lose", "lot", "loud", "love", "lovely", "low", "luck", "lucky", "lunch",
    "machine", "mad", "magazine", "mail", "main", "make", "man", "many", "map", "march",
    "mark", "market", "marry", "match", "math", "matter", "may", "maybe", "me", "meal",
    "mean", "meaning", "meat", "medicine", "meet", "meeting", "member", "memory", "mention",
    "message", "meter", "middle", "might", "mile", "milk", "mind", "mine", "minute", "miss",
    "mistake", "modern", "mom", "moment", "monday", "money", "monkey", "month", "moon",
    "more", "morning", "most", "mother", "mountain", "mouth", "move", "movie", "mr", "mrs",
    "ms", "much", "museum", "music", "must", "my", "myself", "name", "national", "nature",
    "near", "nearly", "necessary", "need", "neighbor", "neither", "never", "new", "news",
    "newspaper", "next", "nice", "night", "nine", "nineteen", "ninety", "no", "nobody",
    "noise", "none", "noon", "nor", "north", "nose", "not", "note", "nothing", "notice",
    "november", "now", "number", "nurse", "o'clock", "ocean", "october", "of", "off",
    "offer", "office", "officer", "often", "oh", "oil", "ok", "old", "on", "once", "one",
    "only", "open", "or", "orange", "order", "other", "our", "ours", "ourselves", "out",
    "outside", "over", "own", "page", "pain", "paint", "pair", "palace", "pale", "paper",
    "parent", "park", "part", "party", "pass", "past", "patient", "pay", "peace", "pear",
    "pen", "pencil", "people", "percent", "perfect", "perhaps", "person", "personal", "pet",
    "phone", "photo", "piano", "pick", "picnic", "picture", "piece", "pig", "pink", "place",
    "plan", "plane", "plant", "plastic", "play", "playground", "please", "pleased", "plenty",
    "pocket", "poem", "point", "police", "polite", "pollution", "pool", "poor", "popular",
    "population", "possible", "post", "potato", "practice", "prepare", "present", "pretty",
    "price", "pride", "primary", "print", "prison", "prize", "probably", "problem", "produce",
    "product", "program", "progress", "project", "promise", "protect", "proud", "provide",
    "public", "pull", "punish", "pupil", "purple", "push", "put", "quarter", "queen",
    "question", "quick", "quiet", "quite", "rabbit", "race", "radio", "railway", "rain",
    "rainy", "raise", "rather", "reach", "read", "ready", "real", "really", "reason",
    "receive", "recent", "red", "refuse", "regret", "relax", "remember", "remind", "repair",
    "repeat", "reply", "report", "rest", "restaurant", "result", "return", "review", "rice",
    "rich", "ride", "right", "ring", "rise", "river", "road", "robot", "rock", "room",
    "rope", "rose", "round", "rule", "run", "sad", "safe", "safety", "said", "same", "sand",
    "sandwich", "saturday", "save", "say", "school", "science", "scientist", "score", "sea",
    "search", "season", "seat", "second", "secret", "see", "seem", "sell", "send",
    "sentence", "september", "serious", "serve", "service", "set", "seven", "seventeen",
    "several", "shake", "shall", "shame", "shape", "share", "she", "sheep", "shine", "ship",
    "shirt", "shoe", "shop", "short", "should", "shoulder", "shout", "show", "shower", "shut",
    "sick", "side", "sight", "sign", "silence", "silent", "silly", "silver", "similar",
    "simple", "since", "sing", "singer", "single", "sir", "sister", "sit", "situation", "six",
    "sixteen", "sixty", "size", "skate", "skill", "skin", "skirt", "sky", "sleep", "slow",
    "small", "smart", "smell", "smile", "smoke", "snow", "so", "soap", "social", "society",
    "soft", "soldier", "solid", "some", "somebody", "someone", "something", "sometimes", "son",
    "song", "soon", "sorry", "sound", "soup", "south", "space", "speak", "special", "speech",
    "speed", "spell", "spend", "spirit", "spoon", "sport", "spring", "square", "stamp",
    "stand", "star", "start", "state", "station", "stay", "steal", "step", "stick", "still",
    "stomach", "stone", "stop", "store", "storm", "story", "straight", "strange", "street",
    "strict", "strong", "student", "study", "stupid", "subject", "success", "successful",
    "such", "sudden", "sugar", "suggest", "summer", "sun", "sunday", "sunny", "supermarket",
    "supper", "sure", "surface", "surprise", "sweater", "sweet", "swim", "table", "take",
    "talk", "tall", "tape", "task", "taste", "taxi", "tea", "teach", "teacher", "team",
    "technology", "telephone", "television", "tell", "temperature", "ten", "tennis", "term",
    "terrible", "test", "text", "than", "thank", "that", "the", "their", "theirs", "them",
    "themselves", "then", "there", "these", "they", "thick", "thin", "thing", "think", "third",
    "thirsty", "thirteen", "thirty", "this", "those", "though", "thought", "thousand", "three",
    "through", "throw", "thursday", "ticket", "tidy", "tie", "tiger", "time", "tired", "to",
    "today", "together", "toilet", "tomato", "tomorrow", "tonight", "too", "tooth", "top",
    "total", "touch", "tour", "towards", "town", "toy", "traffic", "train", "travel", "tree",
    "trip", "trouble", "true", "try", "tuesday", "turn", "twelve", "twenty", "twice", "two",
    "type", "umbrella", "uncle", "under", "understand", "unit", "university", "unless",
    "until", "up", "upon", "us", "use", "useful", "usual", "usually", "vacation", "value",
    "vegetable", "very", "victory", "video", "village", "visit", "visitor", "voice", "wait",
    "wake", "walk", "wall", "want", "warm", "warn", "wash", "waste", "watch", "water", "way",
    "we", "weak", "wear", "weather", "wednesday", "week", "weekend", "weigh", "welcome",
    "well", "west", "wet", "what", "whatever", "when", "where", "whether", "which", "while",
    "white", "who", "whole", "whom", "whose", "why", "wide", "wife", "will", "win", "wind",
    "window", "windy", "wine", "winter", "wise", "wish", "with", "within", "without", "woman",
    "wonder", "wonderful", "wood", "word", "work", "worker", "world", "worry", "worse",
    "worst", "worth", "would", "write", "wrong", "yard", "year", "yellow", "yes", "yesterday",
    "yet", "you", "young", "your", "yours", "yourself", "zero", "zoo",
}

# 高中额外常用词（在初中基础上扩展；造句时可使用初中+高中词）
HIGH_SCHOOL_EXTRA = {
    "abandon", "ability", "abroad", "absence", "absolute", "absorb", "abstract", "abundant",
    "academic", "accept", "access", "accident", "accompany", "accomplish", "according",
    "account", "accurate", "accuse", "achieve", "achievement", "acknowledge", "acquire",
    "action", "active", "activity", "actual", "adapt", "add", "addition", "address", "adequate",
    "adjust", "admire", "admit", "adopt", "adult", "advance", "advantage", "adventure",
    "advertise", "advice", "advise", "affair", "affect", "afford", "afraid", "agency", "agenda",
    "agent", "aggressive", "agriculture", "aid", "aim", "airline", "alarm", "alcohol", "alert",
    "alike", "alive", "allow", "ally", "alongside", "alter", "alternative", "although",
    "altogether", "amaze", "ambition", "ambulance", "amount", "amuse", "analyse", "analysis",
    "ancestor", "ancient", "anger", "angle", "announce", "annoy", "annual", "anxious", "anyway",
    "apart", "apartment", "apologize", "apology", "apparent", "appear", "appearance",
    "application", "apply", "appoint", "appointment", "appreciate", "approach", "appropriate",
    "approve", "approximate", "architect", "architecture", "argue", "argument", "arise",
    "arithmetic", "army", "arrange", "arrest", "arrow", "article", "artificial", "artist",
    "ashamed", "aspect", "assemble", "assess", "assign", "assignment", "assist", "associate",
    "assume", "assumption", "astonish", "athlete", "atmosphere", "attach", "attack", "attempt",
    "attend", "attention", "attitude", "attract", "attraction", "attractive", "audience",
    "author", "authority", "automatic", "available", "average", "avoid", "award", "aware",
    "awareness", "awful", "background", "badly", "balance", "ban", "band", "bang", "bar",
    "bare", "bargain", "barrier", "base", "basic", "basis", "bath", "battery", "battle",
    "bay", "beam", "bean", "bear", "beard", "beast", "beat", "beauty", "beef", "beer",
    "beg", "behave", "behavior", "being", "belief", "belong", "belt", "bench", "bend",
    "benefit", "besides", "betray", "beyond", "bid", "bill", "bind", "biology", "birth",
    "biscuit", "bite", "bitter", "blame", "blank", "blanket", "bleed", "bless", "blind",
    "block", "blood", "bloom", "blouse", "board", "boast", "boil", "bold", "bomb", "bond",
    "bone", "bonus", "boom", "boost", "border", "bore", "bother", "bottom", "bounce", "bound",
    "bow", "bowl", "brain", "branch", "brand", "brave", "breast", "breath", "breathe", "breed",
    "brick", "brief", "brilliant", "broad", "broadcast", "budget", "bunch", "burden", "burn",
    "burst", "bury", "bush", "business", "butter", "button", "cabin", "cable", "cafe",
    "calculate", "calendar", "calm", "camera", "camp", "campaign", "campus", "canal",
    "cancel", "cancer", "candidate", "candle", "capable", "capacity", "capital", "captain",
    "capture", "carbon", "career", "careless", "cargo", "carpenter", "carpet", "carriage",
    "case", "cash", "cast", "castle", "casual", "catalogue", "category", "cattle", "cause",
    "caution", "cave", "cease", "ceiling", "celebrate", "celebration", "cell", "cent",
    "central", "century", "ceremony", "certain", "certificate", "chain", "challenge",
    "champion", "chance", "channel", "chapter", "character", "characteristic", "charge",
    "charity", "charm", "chart", "chase", "chat", "cheat", "check", "cheek", "cheer",
    "cheese", "chemical", "chemistry", "cheque", "chest", "chew", "chief", "chip", "chocolate",
    "choice", "choke", "chop", "christian", "cigarette", "circle", "circumstance", "citizen",
    "civil", "claim", "clap", "clarify", "classical", "classify", "clause", "clay", "clerk",
    "click", "client", "cliff", "climate", "clinic", "clip", "cloth", "cloud", "clue", "coach",
    "coal", "coast", "code", "coin", "collapse", "collar", "colleague", "college", "colony",
    "column", "combat", "combine", "comedy", "comfort", "command", "comment", "commerce",
    "commercial", "commission", "commit", "committee", "communicate", "communication",
    "community", "companion", "company", "compare", "comparison", "compete", "competition",
    "complain", "complaint", "complete", "complex", "complicated", "component", "compose",
    "composition", "compound", "comprehension", "comprehensive", "comprise", "compromise",
    "concentrate", "concept", "concern", "conclude", "conclusion", "concrete", "condition",
    "conduct", "conference", "confidence", "confident", "confirm", "conflict", "confuse",
    "congratulate", "congress", "connect", "connection", "conscience", "conscious", "consequence",
    "conservative", "consider", "considerable", "consideration", "consist", "constant",
    "construct", "construction", "consult", "consume", "consumer", "contact", "contain",
    "container", "contemporary", "content", "contest", "context", "continent", "continue",
    "continuous", "contract", "contrary", "contrast", "contribute", "contribution", "control",
    "controversial", "convenience", "convenient", "convention", "conventional", "conversation",
    "convert", "convince", "cooperate", "cope", "copper", "core", "corn", "corporate",
    "corporation", "correct", "correspond", "corridor", "costly", "cotton", "cough", "council",
    "count", "counter", "county", "couple", "courage", "court", "courtyard", "cousin", "crack",
    "craft", "crash", "crawl", "cream", "create", "creation", "creative", "creature", "credit",
    "crew", "crime", "criminal", "crisis", "criterion", "critic", "critical", "criticism",
    "criticize", "crop", "crowd", "crown", "crucial", "cruel", "crush", "crust", "cry", "cube",
    "cultivate", "culture", "cupboard", "cure", "curious", "curl", "currency", "current",
    "curriculum", "curtain", "curve", "custom", "customer", "cycle", "daily", "dam", "damage",
    "damp", "dare", "dash", "data", "database", "dawn", "debate", "debt", "decade", "decay",
    "deceive", "december", "decent", "decide", "decision", "declare", "decline", "decorate",
    "decrease", "deed", "defeat", "defence", "defend", "deficit", "define", "definite",
    "definition", "degree", "delay", "delete", "deliberate", "delicate", "deliver", "demand",
    "democracy", "democratic", "demonstrate", "dense", "density", "deny", "depart", "department",
    "departure", "depend", "dependent", "deposit", "depress", "depth", "derive", "describe",
    "description", "desert", "deserve", "design", "desire", "desk", "desperate", "despite",
    "destination", "destroy", "destruction", "detail", "detect", "determine", "develop",
    "development", "device", "devote", "diagram", "dialect", "dialogue", "diameter", "diamond",
    "dictate", "dictionary", "diet", "differ", "digest", "digital", "dim", "dimension",
    "dine", "dioxide", "diploma", "direct", "direction", "directly", "director", "dirt",
    "disabled", "disadvantage", "disagree", "disappear", "disappoint", "disaster", "disc",
    "discard", "discipline", "discount", "discourage", "discover", "discovery", "discuss",
    "discussion", "disease", "disgust", "dish", "dislike", "dismiss", "disorder", "display",
    "dispose", "dispute", "distance", "distant", "distinct", "distinction", "distinguish",
    "distribute", "district", "disturb", "dive", "diverse", "divide", "division", "divorce",
    "document", "domestic", "dominant", "dominate", "donate", "donkey", "doorway", "dose",
    "dot", "double", "doubt", "downstairs", "downtown", "downward", "dozen", "draft", "drag",
    "dragon", "drain", "drama", "dramatic", "draw", "drawer", "drawing", "dread", "drill",
    "drown", "drug", "drum", "drunk", "due", "dull", "dumb", "dump", "durable", "duration",
    "dusk", "dust", "duty", "dye", "dynamic", "eager", "eagle", "earn", "earthquake", "ease",
    "eastern", "echo", "economic", "economy", "edge", "edit", "edition", "editor", "educate",
    "education", "effect", "effective", "efficiency", "efficient", "effort", "egg", "ego",
    "eight", "elaborate", "elbow", "elder", "elect", "election", "electric", "electricity",
    "electronic", "elegant", "element", "elementary", "elephant", "eliminate", "else",
    "elsewhere", "email", "embarrass", "embassy", "embrace", "emerge", "emergency", "emotion",
    "emotional", "emphasis", "emphasize", "empire", "employ", "employee", "employer",
    "employment", "empty", "enable", "enclose", "encounter", "encourage", "end", "ending",
    "endless", "endure", "enemy", "energy", "enforce", "engage", "engine", "engineer",
    "enhance", "enjoy", "enlarge", "enormous", "enough", "enquire", "ensure", "enter",
    "enterprise", "entertain", "entertainment", "enthusiasm", "enthusiastic", "entire",
    "entrance", "entry", "envelope", "environment", "environmental", "envy", "episode",
    "equal", "equality", "equation", "equip", "equipment", "equivalent", "era", "error",
    "escape", "especially", "essay", "essential", "establish", "estate", "estimate", "etc",
    "ethnic", "evaluate", "eve", "even", "evening", "event", "eventually", "ever", "every",
    "evidence", "evident", "evil", "evolution", "evolve", "exact", "exaggerate", "exam",
    "examination", "examine", "example", "exceed", "excellent", "except", "exception",
    "exchange", "excite", "exclude", "excuse", "executive", "exercise", "exhaust", "exhibit",
    "exhibition", "exist", "existence", "exit", "expand", "expansion", "expect", "expectation",
    "expense", "expensive", "experience", "experiment", "expert", "explain", "explanation",
    "explode", "exploit", "explore", "explosion", "export", "expose", "express", "expression",
    "extend", "extension", "extensive", "extent", "external", "extra", "extraordinary",
    "extreme", "eye", "fabric", "face", "facility", "fact", "factor", "factory", "faculty",
    "fade", "fail", "failure", "faint", "fair", "fairly", "faith", "fall", "false", "fame",
    "familiar", "family", "famous", "fan", "fancy", "fantastic", "far", "fare", "farm",
    "farmer", "fascinating", "fashion", "fasten", "fat", "fate", "father", "fault", "favor",
    "favorable", "favorite", "fear", "feasible", "feather", "feature", "february", "federal",
    "fee", "feed", "feedback", "feel", "feeling", "fellow", "female", "fence", "fertile",
    "festival", "fetch", "fever", "few", "fiber", "fiction", "field", "fierce", "fifteen",
    "fifth", "fifty", "fight", "figure", "file", "fill", "film", "final", "finance",
    "financial", "find", "finding", "fine", "finger", "finish", "fire", "firm", "first",
    "fish", "fisherman", "fit", "five", "fix", "flag", "flame", "flash", "flat", "flee",
    "flesh", "flexible", "flight", "float", "flood", "floor", "flour", "flow", "flower",
    "flu", "fluent", "fluid", "fly", "focus", "fog", "fold", "folk", "follow", "following",
    "fond", "food", "fool", "foolish", "foot", "football", "for", "forbid", "force",
    "forecast", "forehead", "foreign", "foreigner", "forest", "forever", "forget", "forgive",
    "fork", "form", "formal", "format", "former", "formula", "forth", "fortunate", "fortune",
    "forty", "forum", "forward", "found", "foundation", "fountain", "four", "fourteen",
    "fox", "fraction", "fragile", "frame", "framework", "frank", "free", "freedom",
    "freeze", "frequent", "fresh", "friday", "fridge", "friend", "friendly", "friendship",
    "frighten", "from", "front", "frontier", "frost", "fruit", "frustrate", "fuel", "fulfil",
    "function", "fund", "fundamental", "funeral", "funny", "fur", "furniture", "further",
    "furthermore", "future", "gain", "gallery", "gallon", "game", "gang", "gap", "garage",
    "garbage", "garden", "garlic", "gas", "gate", "gather", "gay", "gaze", "gear", "gender",
    "gene", "general", "generate", "generation", "generous", "genius", "gentle", "gentleman",
    "genuine", "geography", "gesture", "get", "ghost", "giant", "gift", "gifted", "girl",
    "give", "glad", "glance", "glass", "global", "globe", "glory", "glove", "glow", "glue",
    "go", "goal", "goat", "god", "gold", "golden", "golf", "good", "goods", "goose",
    "govern", "government", "governor", "grab", "grace", "grade", "gradual", "graduate",
    "grain", "grammar", "grand", "grandfather", "grandmother", "grant", "grape", "graph",
    "grasp", "grass", "grateful", "grave", "gravity", "gray", "great", "greedy", "green",
    "greet", "grey", "grocery", "ground", "group", "grow", "growth", "guarantee", "guard",
    "guess", "guest", "guidance", "guide", "guilty", "guitar", "gun", "guy", "gym", "habit",
    "habitat", "hair", "half", "hall", "halt", "ham", "hamburger", "hammer", "hand",
    "handbag", "handful", "handle", "handsome", "handwriting", "hang", "happen", "happiness",
    "happy", "harbor", "hard", "hardly", "harm", "harmful", "harmony", "harsh", "harvest",
    "hat", "hate", "hatred", "have", "hazard", "he", "head", "headache", "headline",
    "headmaster", "headquarters", "heal", "health", "healthy", "heap", "hear", "hearing",
    "heart", "heat", "heaven", "heavily", "heavy", "hedge", "heel", "height", "helicopter",
    "hell", "hello", "helmet", "help", "helpful", "helpless", "hen", "hence", "her", "herb",
    "here", "hero", "hers", "herself", "hesitate", "hi", "hide", "high", "highlight",
    "highly", "highway", "hill", "him", "himself", "hint", "hip", "hire", "his", "historian",
    "historic", "historical", "history", "hit", "hobby", "hold", "hole", "holiday", "hollow",
    "holy", "home", "homeland", "homeless", "homework", "honest", "honey", "honor", "hook",
    "hope", "hopeful", "horizon", "horn", "horror", "horse", "hospital", "host", "hostage",
    "hostess", "hostile", "hot", "hotel", "hour", "house", "household", "housewife",
    "housework", "housing", "how", "however", "hug", "huge", "human", "humble", "humor",
    "humorous", "hundred", "hunger", "hungry", "hunt", "hunter", "hurricane", "hurry", "hurt",
    "husband", "hut", "hydrogen", "ice", "idea", "ideal", "identical", "identify", "identity",
    "idiom", "idle", "if", "ignore", "ill", "illegal", "illness", "illustrate", "image",
    "imaginary", "imagination", "imagine", "imitate", "immediate", "immediately", "immigrant",
    "impact", "impatient", "implication", "imply", "import", "importance", "important",
    "impose", "impossible", "impress", "impression", "impressive", "improve", "improvement",
    "in", "inch", "incident", "include", "income", "increase", "increasingly", "indeed",
    "independence", "independent", "index", "indicate", "indication", "individual", "indoor",
    "industrial", "industry", "inevitable", "infant", "infect", "infection", "infer",
    "inflation", "influence", "inform", "information", "ingredient", "inhabitant", "inherit",
    "initial", "initiative", "injure", "injury", "inner", "innocent", "innovation", "input",
    "inquire", "insect", "insert", "inside", "insight", "insist", "inspect", "inspire",
    "install", "instance", "instant", "instead", "institute", "institution", "instruct",
    "instruction", "instrument", "insurance", "insure", "intellectual", "intelligence",
    "intelligent", "intend", "intense", "intention", "interaction", "interest", "interesting",
    "interfere", "internal", "international", "internet", "interpret", "interrupt", "interval",
    "interview", "into", "introduce", "introduction", "invade", "invent", "invention",
    "invest", "investigate", "investigation", "investment", "invite", "involve", "iron",
    "island", "issue", "it", "item", "its", "itself", "jacket", "jam", "january", "jar",
    "jaw", "jazz", "jealous", "jeans", "jet", "jewel", "job", "join", "joint", "joke",
    "journal", "journalist", "journey", "joy", "judge", "judgment", "juice", "july", "jump",
    "june", "jungle", "junior", "jury", "just", "justice", "justify", "keen", "keep", "kettle",
    "key", "keyboard", "kick", "kid", "kill", "kilo", "kilogram", "kilometer", "kind",
    "kindergarten", "king", "kingdom", "kiss", "kitchen", "kite", "knee", "kneel", "knife",
    "knock", "know", "knowledge", "lab", "label", "labor", "laboratory", "lack", "ladder",
    "lady", "lake", "lamb", "lame", "lamp", "land", "landing", "landlord", "landscape",
    "lane", "language", "lap", "large", "largely", "laser", "last", "late", "lately", "later",
    "latest", "latter", "laugh", "laughter", "launch", "laundry", "law", "lawn", "lawyer",
    "lay", "layer", "lazy", "lead", "leader", "leadership", "leading", "leaf", "league",
    "leak", "lean", "leap", "learn", "learned", "least", "leather", "leave", "lecture", "left",
    "leg", "legal", "legend", "leisure", "lemon", "lend", "length", "lens", "less", "lesson",
    "lest", "let", "letter", "level", "liberal", "liberty", "librarian", "library", "license",
    "lid", "lie", "life", "lifetime", "lift", "light", "lightning", "like", "likely", "limit",
    "limitation", "limited", "line", "link", "lion", "lip", "liquid", "list", "listen",
    "literacy", "literary", "literature", "liter", "little", "live", "lively", "living",
    "load", "loaf", "loan", "local", "locate", "location", "lock", "log", "logic", "logical",
    "lonely", "long", "look", "loose", "lord", "lorry", "lose", "loss", "lot", "loud", "love",
    "lovely", "lover", "low", "lower", "loyal", "loyalty", "luck", "lucky", "luggage", "lunch",
    "lung", "luxury", "machine", "mad", "magazine", "magic", "magnetic", "magnificent",
    "mail", "main", "mainland", "mainly", "maintain", "maintenance", "major", "majority",
    "make", "male", "man", "manage", "management", "manager", "mankind", "manner", "manual",
    "manufacture", "manufacturer", "many", "map", "march", "margin", "marine", "mark",
    "market", "marriage", "married", "marry", "marvelous", "mask", "mass", "massive",
    "master", "match", "mate", "material", "math", "mathematical", "mathematics", "matter",
    "mature", "maximum", "may", "maybe", "mayor", "me", "meal", "mean", "meaning", "means",
    "meanwhile", "measure", "meat", "mechanic", "mechanical", "mechanism", "media", "medical",
    "medicine", "medium", "meet", "meeting", "melt", "member", "membership", "memorial",
    "memory", "mend", "mental", "mention", "menu", "merchant", "mercy", "mere", "merely",
    "merit", "mess", "message", "metal", "method", "metre", "microphone", "microscope",
    "midday", "middle", "midnight", "midst", "might", "mild", "mile", "military", "milk",
    "mill", "millimeter", "million", "mind", "mine", "mineral", "minimum", "minister",
    "ministry", "minor", "minority", "minus", "minute", "miracle", "mirror", "miserable",
    "mislead", "miss", "missile", "missing", "mission", "mistake", "mix", "mixture", "mobile",
    "mode", "model", "moderate", "modern", "modest", "modify", "moment", "monday", "money",
    "monitor", "monkey", "month", "monthly", "monument", "mood", "moon", "moral", "more",
    "moreover", "morning", "mosquito", "most", "mostly", "mother", "motion", "motivate",
    "motive", "motor", "mount", "mountain", "mouse", "mouth", "move", "movement", "movie",
    "much", "mud", "multiple", "multiply", "murder", "muscle", "museum", "mushroom", "music",
    "musical", "musician", "must", "mutual", "my", "myself", "mysterious", "mystery", "nail",
    "naked", "name", "namely", "narrative", "narrow", "nation", "national", "native",
    "natural", "nature", "navy", "near", "nearby", "nearly", "neat", "necessarily",
    "necessary", "neck", "need", "needle", "negative", "neglect", "negotiate", "negotiation",
    "neighbor", "neighborhood", "neither", "nephew", "nerve", "nervous", "nest", "net",
    "network", "neutral", "never", "nevertheless", "new", "newly", "news", "newspaper",
    "next", "nice", "niece", "night", "nine", "nineteen", "ninety", "no", "noble", "nobody",
    "nod", "noise", "noisy", "none", "nonsense", "noon", "nor", "norm", "normal", "normally",
    "north", "northern", "nose", "not", "note", "notebook", "nothing", "notice", "notion",
    "novel", "november", "now", "nowadays", "nowhere", "nuclear", "number", "numerous",
    "nurse", "nursery", "nut", "nutrition", "nylon", "obey", "object", "objection",
    "objective", "obligation", "observation", "observe", "observer", "obtain", "obvious",
    "occasion", "occasional", "occupation", "occupy", "occur", "ocean", "o'clock", "october",
    "odd", "of", "off", "offend", "offense", "offer", "office", "officer", "official",
    "often", "oh", "oil", "ok", "old", "on", "once", "one", "oneself", "onion", "online",
    "only", "onto", "open", "opening", "opera", "operate", "operation", "operator", "opinion",
    "opponent", "opportunity", "oppose", "opposite", "opposition", "opt", "optimistic",
    "option", "or", "oral", "orange", "orbit", "orchestra", "order", "ordinary", "organ",
    "organic", "organization", "organize", "origin", "original", "other", "otherwise",
    "ought", "our", "ours", "ourselves", "out", "outcome", "outdoor", "outer", "outline",
    "outlook", "output", "outside", "outstanding", "outward", "oven", "over", "overall",
    "overcome", "overhead", "overlook", "overnight", "overseas", "overtake", "owe", "own",
    "owner", "ownership", "ox", "oxygen", "pace", "pack", "package", "packet", "pad", "page",
    "pain", "painful", "paint", "painter", "painting", "pair", "palace", "pale", "pan",
    "panel", "panic", "pants", "paper", "parade", "paragraph", "parallel", "parcel", "pardon",
    "parent", "park", "parking", "parliament", "part", "participate", "particular",
    "particularly", "partly", "partner", "party", "pass", "passage", "passenger", "passion",
    "passive", "passport", "past", "paste", "pat", "patch", "path", "patience", "patient",
    "pattern", "pause", "pave", "pay", "payment", "pea", "peace", "peaceful", "peak", "pear",
    "peasant", "peculiar", "peer", "pen", "penalty", "pencil", "penny", "pension", "people",
    "pepper", "per", "perceive", "percent", "percentage", "perception", "perfect", "perform",
    "performance", "performer", "perhaps", "period", "permanent", "permission", "permit",
    "persist", "person", "personal", "personality", "personally", "personnel", "perspective",
    "persuade", "pet", "petrol", "phase", "phenomenon", "philosopher", "philosophy", "phone",
    "photo", "photograph", "photographer", "phrase", "physical", "physician", "physics",
    "piano", "pick", "picnic", "picture", "pie", "piece", "pig", "pile", "pill", "pillow",
    "pilot", "pin", "pinch", "pine", "pink", "pint", "pioneer", "pipe", "pity", "place",
    "plain", "plan", "plane", "planet", "plant", "plastic", "plate", "platform", "play",
    "player", "playground", "pleasant", "please", "pleased", "pleasure", "plenty", "plot",
    "plug", "plus", "pocket", "poem", "poet", "poetry", "point", "poison", "pole", "police",
    "policeman", "policy", "polish", "polite", "political", "politician", "politics", "poll",
    "pollute", "pollution", "pond", "pool", "poor", "pop", "popular", "population", "pork",
    "port", "portable", "porter", "portion", "portrait", "position", "positive", "possess",
    "possession", "possibility", "possible", "possibly", "post", "postage", "postcard",
    "poster", "postman", "postpone", "pot", "potato", "potential", "pound", "pour", "poverty",
    "powder", "power", "powerful", "practical", "practice", "praise", "pray", "prayer",
    "precious", "precise", "predict", "prefer", "preference", "pregnant", "prejudice",
    "preliminary", "premier", "preparation", "prepare", "presence", "present", "presentation",
    "preserve", "president", "press", "pressure", "pretend", "pretty", "prevail", "prevent",
    "previous", "price", "pride", "priest", "primary", "prime", "primitive", "prince",
    "princess", "principal", "principle", "print", "printer", "prior", "priority", "prison",
    "prisoner", "privacy", "private", "privilege", "prize", "probability", "probable",
    "probably", "problem", "procedure", "proceed", "process", "produce", "producer",
    "product", "production", "profession", "professional", "professor", "profit", "program",
    "progress", "prohibit", "project", "prominent", "promise", "promote", "prompt", "pronoun",
    "pronounce", "pronunciation", "proof", "proper", "property", "proportion", "proposal",
    "propose", "prospect", "protect", "protection", "protein", "protest", "proud", "prove",
    "provide", "province", "provision", "psychological", "psychology", "pub", "public",
    "publication", "publicity", "publish", "pull", "pulse", "pump", "punch", "punctual",
    "punish", "punishment", "pupil", "purchase", "pure", "purple", "purpose", "purse",
    "pursue", "push", "put", "puzzle", "qualification", "qualify", "quality", "quantity",
    "quarrel", "quarter", "queen", "question", "questionnaire", "queue", "quick", "quiet",
    "quit", "quite", "quiz", "quotation", "quote", "rabbit", "race", "racial", "radiation",
    "radical", "radio", "rag", "rail", "railway", "rain", "rainbow", "raincoat", "rainy",
    "raise", "range", "rank", "rapid", "rare", "rarely", "rat", "rate", "rather", "ratio",
    "raw", "ray", "reach", "react", "reaction", "read", "reader", "readily", "reading",
    "ready", "real", "realistic", "reality", "realize", "really", "rear", "reason",
    "reasonable", "recall", "receipt", "receive", "recent", "recently", "reception", "recipe",
    "reckon", "recognition", "recognize", "recommend", "recommendation", "record", "recover",
    "recovery", "recreation", "recruit", "red", "reduce", "reduction", "refer", "reference",
    "reflect", "reform", "refuse", "regard", "regarding", "regardless", "region", "regional",
    "register", "regret", "regular", "regulate", "regulation", "reinforce", "reject", "relate",
    "relation", "relationship", "relative", "relax", "release", "relevant", "reliable",
    "relief", "relieve", "religion", "religious", "reluctant", "rely", "remain", "remark",
    "remarkable", "remedy", "remember", "remind", "remote", "removal", "remove", "render",
    "renew", "rent", "repair", "repeat", "replace", "reply", "report", "reporter", "represent",
    "representative", "reputation", "request", "require", "requirement", "rescue", "research",
    "researcher", "resemble", "reserve", "reservoir", "residence", "resident", "resign",
    "resist", "resistance", "resolution", "resolve", "resource", "respect", "respective",
    "respond", "response", "responsibility", "responsible", "rest", "restaurant", "restore",
    "restrict", "result", "resume", "retail", "retain", "retire", "retreat", "return",
    "reveal", "revenue", "reverse", "review", "revise", "revolution", "reward", "rhythm",
    "rice", "rich", "rid", "ride", "ridge", "ridiculous", "right", "rigid", "ring", "rise",
    "risk", "rival", "river", "road", "roar", "roast", "rob", "robot", "rock", "rocket",
    "rod", "role", "roll", "romantic", "roof", "room", "root", "rope", "rose", "rough",
    "round", "route", "routine", "row", "royal", "rub", "rubber", "rubbish", "rude", "rug",
    "ruin", "rule", "ruler", "rumor", "run", "rural", "rush", "rust", "sacred", "sacrifice",
    "sad", "safe", "safety", "sail", "sailor", "sake", "salad", "salary", "sale", "salesman",
    "salt", "same", "sample", "sand", "sandwich", "satellite", "satisfaction", "satisfy",
    "saturday", "sauce", "saucer", "sausage", "save", "saving", "say", "scale", "scan",
    "scarce", "scare", "scatter", "scene", "scenery", "schedule", "scheme", "scholar",
    "scholarship", "school", "science", "scientific", "scientist", "scissors", "scold",
    "scope", "score", "scratch", "scream", "screen", "script", "sea", "seal", "search",
    "season", "seat", "second", "secondary", "secret", "secretary", "section", "sector",
    "secure", "security", "see", "seed", "seek", "seem", "seize", "seldom", "select",
    "selection", "self", "sell", "semester", "seminar", "send", "senior", "sense", "sensible",
    "sensitive", "sentence", "separate", "september", "sequence", "series", "serious",
    "servant", "serve", "service", "session", "set", "settle", "settlement", "seven",
    "seventeen", "several", "severe", "sew", "sex", "sexual", "shade", "shadow", "shake",
    "shall", "shallow", "shame", "shape", "share", "sharp", "shave", "she", "sheep", "sheet",
    "shelf", "shell", "shelter", "shift", "shine", "ship", "shirt", "shock", "shoe", "shoot",
    "shop", "shore", "short", "shortage", "shortly", "shot", "should", "shoulder", "shout",
    "show", "shower", "shrink", "shut", "shy", "sick", "side", "sidewalk", "sigh", "sight",
    "sightseeing", "sign", "signal", "signature", "significance", "significant", "silence",
    "silent", "silk", "silly", "silver", "similar", "simple", "simply", "sin", "since",
    "sincere", "sing", "singer", "single", "sink", "sir", "sister", "sit", "site", "situation",
    "six", "sixteen", "sixty", "size", "skate", "sketch", "ski", "skill", "skilled", "skin",
    "skirt", "sky", "slave", "sleep", "slice", "slide", "slight", "slim", "slip", "slope",
    "slow", "small", "smart", "smell", "smile", "smoke", "smooth", "snake", "snow", "so",
    "soap", "soar", "social", "socialism", "society", "sock", "soda", "sofa", "soft",
    "software", "soil", "solar", "soldier", "sole", "solid", "solution", "solve", "some",
    "somebody", "somehow", "someone", "something", "sometime", "sometimes", "somewhat", "son",
    "song", "soon", "sophisticated", "sore", "sorrow", "sorry", "sort", "soul", "sound",
    "soup", "sour", "source", "south", "southeast", "southern", "southwest", "souvenir",
    "sow", "space", "spacecraft", "spade", "span", "spare", "spark", "speak", "speaker",
    "special", "specialist", "specialize", "species", "specific", "specify", "speech", "speed",
    "spell", "spelling", "spend", "sphere", "spider", "spill", "spin", "spirit", "spiritual",
    "spit", "spite", "splendid", "split", "spoil", "spoken", "spokesman", "sponsor", "spoon",
    "sport", "spot", "spray", "spread", "spring", "square", "squeeze", "stable", "stadium",
    "staff", "stage", "stain", "stair", "stake", "stamp", "stand", "standard", "star",
    "stare", "start", "starve", "state", "statement", "station", "statistic", "statue",
    "status", "stay", "steady", "steak", "steal", "steam", "steel", "steep", "steer", "stem",
    "step", "steward", "stick", "stiff", "still", "stimulate", "stir", "stock", "stocking",
    "stomach", "stone", "stop", "storage", "store", "storm", "story", "stove", "straight",
    "strain", "strange", "stranger", "strap", "strategic", "strategy", "straw", "stream",
    "street", "strength", "strengthen", "stress", "stretch", "strict", "strike", "string",
    "strip", "stripe", "stroke", "strong", "structure", "struggle", "student", "studio",
    "study", "stuff", "stupid", "style", "subject", "submarine", "submit", "subsequent",
    "substance", "substantial", "substitute", "subtract", "suburb", "subway", "succeed",
    "success", "successful", "such", "suck", "sudden", "suffer", "sufficient", "sugar",
    "suggest", "suggestion", "suit", "suitable", "suitcase", "sum", "summary", "summer",
    "sun", "sunday", "sunlight", "sunny", "sunrise", "sunset", "sunshine", "super", "superb",
    "superior", "supermarket", "supper", "supplement", "supply", "support", "suppose",
    "supreme", "sure", "surely", "surface", "surgery", "surplus", "surprise", "surround",
    "surrounding", "survey", "survival", "survive", "suspect", "suspend", "sustain", "swallow",
    "swear", "sweat", "sweater", "sweep", "sweet", "swell", "swift", "swim", "swing", "switch",
    "sword", "symbol", "sympathy", "symptom", "system", "table", "tablet", "tackle", "tag",
    "tail", "tailor", "take", "tale", "talent", "talk", "tall", "tank", "tap", "tape",
    "target", "task", "taste", "tax", "taxi", "tea", "teach", "teacher", "teaching", "team",
    "tear", "technical", "technique", "technology", "teenager", "telegram", "telephone",
    "telescope", "television", "tell", "temper", "temperature", "temple", "temporary", "ten",
    "tend", "tendency", "tender", "tennis", "tense", "tension", "tent", "term", "terminal",
    "terrible", "territory", "terror", "test", "text", "textbook", "than", "thank", "that",
    "the", "theater", "theatre", "theft", "their", "theirs", "them", "theme", "themselves",
    "then", "theory", "there", "therefore", "these", "they", "thick", "thief", "thin", "thing",
    "think", "thinking", "third", "thirst", "thirsty", "thirteen", "thirty", "this", "thorough",
    "those", "though", "thought", "thousand", "thread", "threat", "threaten", "three",
    "throat", "through", "throughout", "throw", "thumb", "thunder", "thursday", "thus",
    "ticket", "tide", "tidy", "tie", "tiger", "tight", "till", "time", "timetable", "tin",
    "tiny", "tip", "tire", "tired", "tissue", "title", "to", "tobacco", "today", "toe",
    "together", "toilet", "tolerate", "tomato", "tomorrow", "ton", "tone", "tongue", "tonight",
    "too", "tool", "tooth", "top", "topic", "torch", "torture", "total", "touch", "tough",
    "tour", "tourism", "tourist", "toward", "towards", "towel", "tower", "town", "toy",
    "trace", "track", "trade", "tradition", "traditional", "traffic", "tragedy", "train",
    "training", "transfer", "transform", "translate", "translation", "transparent", "transport",
    "trap", "travel", "traveler", "tray", "treasure", "treat", "treatment", "treaty", "tree",
    "tremble", "tremendous", "trend", "trial", "triangle", "trick", "trigger", "trip",
    "triumph", "troop", "tropical", "trouble", "trousers", "truck", "true", "truly", "trunk",
    "trust", "truth", "try", "tube", "tuesday", "tune", "tunnel", "turn", "twelve", "twenty",
    "twice", "twin", "twist", "two", "type", "typewriter", "typical", "tyre", "ugly",
    "ultimate", "umbrella", "unable", "uncle", "under", "undergo", "undergraduate",
    "underground", "underline", "understand", "understanding", "undertake", "undo",
    "undoubtedly", "uneasy", "unemployment", "unexpected", "unfair", "unfortunate", "uniform",
    "union", "unique", "unit", "unite", "united", "unity", "universal", "universe",
    "university", "unknown", "unless", "unlike", "unlikely", "until", "unusual", "up",
    "update", "upon", "upper", "upright", "upset", "upstairs", "upward", "urban", "urge",
    "urgent", "us", "usage", "use", "used", "useful", "useless", "user", "usual", "usually",
    "utility", "utilize", "vacation", "vacuum", "vague", "vain", "valid", "valley", "valuable",
    "value", "van", "vanish", "variety", "various", "vary", "vase", "vast", "vegetable",
    "vehicle", "venture", "verb", "verify", "version", "versus", "vertical", "very", "vessel",
    "veteran", "via", "vice", "victim", "victory", "video", "view", "viewpoint", "village",
    "vinegar", "violate", "violence", "violent", "violet", "violin", "virtual", "virus",
    "visa", "visible", "vision", "visit", "visitor", "visual", "vital", "vitamin", "vivid",
    "vocabulary", "voice", "volcano", "volleyball", "volt", "volume", "voluntary", "volunteer",
    "vote", "voyage", "wage", "wagon", "waist", "wait", "waiter", "waitress", "wake", "walk",
    "wall", "wallet", "wander", "want", "war", "ward", "warehouse", "warm", "warmth", "warn",
    "warning", "wash", "waste", "watch", "water", "waterfall", "watermelon", "wave", "way",
    "we", "weak", "weakness", "wealth", "wealthy", "weapon", "wear", "weather", "web",
    "website", "wedding", "wednesday", "weed", "week", "weekday", "weekend", "weekly",
    "weep", "weigh", "weight", "welcome", "welfare", "well", "west", "western", "wet", "what",
    "whatever", "wheat", "wheel", "when", "whenever", "where", "whereas", "wherever",
    "whether", "which", "whichever", "while", "whisper", "whistle", "white", "who", "whoever",
    "whole", "whom", "whose", "why", "wide", "widespread", "widow", "width", "wife", "wild",
    "will", "willing", "win", "wind", "window", "wine", "wing", "winner", "winter", "wipe",
    "wire", "wisdom", "wise", "wish", "wit", "with", "withdraw", "within", "without",
    "witness", "wolf", "woman", "wonder", "wonderful", "wood", "wooden", "wool", "word",
    "work", "worker", "workforce", "working", "workplace", "workshop", "world", "worldwide",
    "worm", "worn", "worried", "worry", "worse", "worship", "worst", "worth", "worthwhile",
    "worthy", "would", "wound", "wrap", "wrist", "write", "writer", "writing", "wrong",
    "yard", "yawn", "year", "yearly", "yell", "yellow", "yes", "yesterday", "yet", "yield",
    "you", "young", "youngster", "your", "yours", "yourself", "youth", "zero", "zone", "zoo",
}


def get_allowed_vocab(level: str) -> frozenset[str]:
    """返回对应难度允许使用的词汇集合（结果缓存，调用方请勿修改返回的集合）。"""
    if level == "middle":
        return _MIDDLE_ALLOWED
    # 高中 = 初中 + 高中扩展
    return _HIGH_ALLOWED


_MIDDLE_ALLOWED = frozenset(MIDDLE_SCHOOL_CORE)
_HIGH_ALLOWED = frozenset(MIDDLE_SCHOOL_CORE | HIGH_SCHOOL_EXTRA)


def level_label(level: str) -> str:
    return "初中" if level == "middle" else "高中"
